# .goreleaser.yml  – minimal but valid
version: 2

project_name: loghub         # the final binary name

builds:
  - id: loghub
    main: .                  # <-- change if your main.go lives elsewhere
    goarch:
      - amd64
      - arm64
    goos:
      - windows
      - linux
      - darwin
    ldflags:
      - -s -w                # strip debug symbols

archives:
  - id: default
    format: zip              # tar.gz also works
    files:
      - license*             # include a license if you add one

# Disable publish/announce until you’re ready
release:
  draft: true
  disable: true

checksum:
  name_template: 'checksums.txt'

signs:                           # optional – requires gpg or age key
  - artifacts: checksum
    cmd: cosign
    args: ['sign-blob', '--yes', '${artifact}']

brews:                           # Homebrew tap formula
  - name: loghub
    repository:
      owner: VanshikaaGuptaa
      name: homebrew-tap
    homepage: https://github.com/VanshikaaGuptaa/loghub
    description: "Local log aggregator CLI"
    install: |
      bin.install "loghub"

scoops:                           # Homebrew tap formula
  - name: loghub
    repository:
      owner: VanshikaaGuptaa
      name: scoop-bucket